/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiInternalCustodyProvisionRouteImport } from './routes/api/internal/custody/provision'
import { Route as ApiPublicSignerRpcSelftestRouteImport } from './routes/api/public/signer/rpc-selftest'
import { Route as ApiPublicSignerSelftestRouteImport } from './routes/api/public/signer/selftest'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInternalCustodyProvisionRoute =
  ApiInternalCustodyProvisionRouteImport.update({
    id: '/api/internal/custody/provision',
    path: '/api/internal/custody/provision',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSignerRpcSelftestRoute =
  ApiPublicSignerRpcSelftestRouteImport.update({
    id: '/api/public/signer/rpc-selftest',
    path: '/api/public/signer/rpc-selftest',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSignerSelftestRoute = ApiPublicSignerSelftestRouteImport.update({
  id: '/api/public/signer/selftest',
  path: '/api/public/signer/selftest',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/internal/custody/provision': typeof ApiInternalCustodyProvisionRoute
  '/api/public/signer/rpc-selftest': typeof ApiPublicSignerRpcSelftestRoute
  '/api/public/signer/selftest': typeof ApiPublicSignerSelftestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/internal/custody/provision': typeof ApiInternalCustodyProvisionRoute
  '/api/public/signer/rpc-selftest': typeof ApiPublicSignerRpcSelftestRoute
  '/api/public/signer/selftest': typeof ApiPublicSignerSelftestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/internal/custody/provision': typeof ApiInternalCustodyProvisionRoute
  '/api/public/signer/rpc-selftest': typeof ApiPublicSignerRpcSelftestRoute
  '/api/public/signer/selftest': typeof ApiPublicSignerSelftestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/internal/custody/provision'
    | '/api/public/signer/rpc-selftest'
    | '/api/public/signer/selftest'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/internal/custody/provision'
    | '/api/public/signer/rpc-selftest'
    | '/api/public/signer/selftest'
  id:
    | '__root__'
    | '/'
    | '/api/internal/custody/provision'
    | '/api/public/signer/rpc-selftest'
    | '/api/public/signer/selftest'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiInternalCustodyProvisionRoute: typeof ApiInternalCustodyProvisionRoute
  ApiPublicSignerRpcSelftestRoute: typeof ApiPublicSignerRpcSelftestRoute
  ApiPublicSignerSelftestRoute: typeof ApiPublicSignerSelftestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/custody/provision': {
      id: '/api/internal/custody/provision'
      path: '/api/internal/custody/provision'
      fullPath: '/api/internal/custody/provision'
      preLoaderRoute: typeof ApiInternalCustodyProvisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/signer/rpc-selftest': {
      id: '/api/public/signer/rpc-selftest'
      path: '/api/public/signer/rpc-selftest'
      fullPath: '/api/public/signer/rpc-selftest'
      preLoaderRoute: typeof ApiPublicSignerRpcSelftestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/signer/selftest': {
      id: '/api/public/signer/selftest'
      path: '/api/public/signer/selftest'
      fullPath: '/api/public/signer/selftest'
      preLoaderRoute: typeof ApiPublicSignerSelftestRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiInternalCustodyProvisionRoute: ApiInternalCustodyProvisionRoute,
  ApiPublicSignerRpcSelftestRoute: ApiPublicSignerRpcSelftestRoute,
  ApiPublicSignerSelftestRoute: ApiPublicSignerSelftestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
